# Generated by Django 4.2.9 on 2024-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/profile/avatar.png', upload_to='profile_images'),
        ),
    ]
