# Generated by Django 4.2.9 on 2024-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/product_images/placeholder.jpg', null=True, upload_to='product_images/'),
        ),
    ]
